export const eg_stores = [
  'BOX',
  'Favors! by cbr',
  'Parfümerie Akzente',
  'Tally Weijl',
  'Toni Tänzer Platform',
  'REWE',
  'Sparkasse',
  'Schlüsseldienst Phonerep',
  'Bruzzes Weinwelt',
  'Kinderbetreuung',
  'Quickschuh',
  'Penny',
  'Kamps',
  'Woll-Studio',
  'Takko Fashion',
  'Trendstore',
  'Setzer',
  'Alona Schmuck',
  'Optikwelt',
  'Telekom Shop',
  'Grabert',
  'Cafe im Ö',
];

export const ug_stores = [
  'Modehaus Bär',
  'Injoy',
  'Intersport Grabert',
  'Shoetown Werdich',
  'Brautmoden Fabian',
  'Haucks Schnitzelwelt',
  'Vielseitig Bücher',
  'Team 5',
];

export const bus_1 = [
  'Neuperlach Süd',
  'Neubiberg, W.-Heisenberg-W.',
  'Neubiberg',
  'Neubiberg, Rathaus',
  'Neubiberg, Kaiserstraße',
  'Neubiberg, Barbarossastraße',
  'Neubiberg, Schulzstraße',
  'Neubiberg, Gymnasium',
  'Ottobrunn, Erlenstr.',
  'Ottobrunn, Lenbachallee',
  'Ottobrunn, Waldstraße',
  'Putzbrunn, Birkenweg',
  'Putzbrunn, Eichenstraße',
  'Putzbrunn, Brennerei',
  'Putzbrunn, Kirchenzentrum',
];

export const bus_2 = [
  'Neuperlach Süd',
  'Neubiberg, W.-Heisenberg-W.',
  'Neubiberg',
  'Neubiberg, Rathaus',
  'Neubiberg, Kaiserstraße',
  'Neubiberg, Barbarossastraße',
  'Neubiberg, Schulzstraße',
  'Neubiberg, Wotanstraße',
  'Neubiberg, Lena-Christ-Straße',
  'Neubiberg, Anzengruberstr.',
  'Putzbrunn, Neubiberger Straße',
  'Putzbrunn, Isarweg',
];
